services:
  - type: web
    name: sceap-backend
    runtime: python
    buildCommand: pip install -q poetry && poetry install --cwd backend
    startCommand: poetry run uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free

  - type: web
    name: sceap-frontend
    runtime: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: npm install -g serve && serve -s frontend/dist -l $PORT
    plan: free
